spring.application.name=crypto-trading-platform

spring.datasource.url=jdbc:mysql://localhost:3306/trading
spring.datasource.username=root
#spring.datasource.password=Shreyash@3
spring.datasource.password=Hellosam@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
#server.port=9090

# coingecko api key
coingecko.api.key=CG-Bu1h5DVb5nBUqLnsLLUnZnfy

#razorpay key id and key secret
razorpay.key.id=rzp_test_CSYZqx7EFJX8to
razorpay.key.secret=b9hbxH1xjTC7jV6gp7GH6LbF
